apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.storage.name }}
  labels:
    app: vprodb
spec:
  accessModes:
    - {{ .Values.storage.accessMode }}
  resources:
    requests:
      storage: 3Gi
  storageClassName: default
