apiVersion: v1
kind: Service
metadata:
  name: vprodb
spec:
  selector:
    app: vprodb
  ports:
  - port: {{ .Values.db.service.port }}
    targetPort: vprodb-port
    protocol: TCP
  type: {{ .Values.db.service.type }}
