apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vpro-ingress
  annotations:
# nindent is used to add indentation to the YAML output of the toYaml function
  {{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
  - host: {{ (index .Values.ingress.hosts 0).host }}
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: vproapp-svc
            port: 
              number: 8080
