apiVersion: v1
kind: Service
metadata:
  name: vprocache01
spec:
  selector:
    app: vpromc
  ports:
  - port: {{ .Values.memcache.service.port }}
    targetPort: vpromc-port
    protocol: TCP
  type: {{ .Values.memcache.service.type }}
